export enum RouterPathNameEnum {
  HOME = '/',
  MOVIES = '/movies',
  TVS = '/tvs',
  SEARCH = '/search',
  TRENDING_MOVIES = '/movies/trending',
  POPULAR_MOVIES = '/movies/popular',
  NOW_PLAYING_MOVIES = '/movies/now-playing',
  UPCOMING_MOVIES = '/movies/upcoming',
  TOP_RATED_MOVIES = '/movies/top-rated',
  GENRE_MOVIES = '/movies/genre',
  TRENDING_TVS = '/tvs/trending',
  POPULAR_TVS = '/tvs/popular',
  AIRING_TODAY_TVS = '/tvs/airing-today',
  ON_AIR_TVS = '/tvs/on-air',
  TOP_RATED_TVS = '/tvs/top-rated',
  GENRE_TVS = '/tvs/genre',
}
